server.port: 8079
management:
  endpoints:
    web:
      exposure:
        include: prometheus
spring:
  application:
    name: kafkaproducer
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: "http://localhost:8085"

kafka:
  topic:
    names:
      mytopic: pedroalmeida.eventTopic