apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - image: kafka-producer:latest
          name: kafka-producer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8079
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: kafka:29092
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: org.apache.kafka.common.serialization.StringSerializer
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: io.confluent.kafka.serializers.KafkaAvroSerializer
            - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
              value: http://schemaregistry:8085
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  type: NodePort
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
      nodePort: 30179