apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mariadb.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mariadb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mariadb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mariadb.name }}
    spec:
      containers:
        - name: {{ .Values.mariadb.name }}
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: mariadb-url
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-root

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mariadb.name }}
spec:
  selector:
    app: {{ .Values.mariadb.name }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  mariadb-root: cm9vdA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  mariadb-url: {{ .Values.mariadb.name }}