apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.zookeeper }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.zookeeper }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper }}
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:latest
          imagePullPolicy: IfNotPresent
          name: {{ .Values.zookeeper }}
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.zookeeper }}
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: {{ .Values.zookeeper }}