apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  strategy: { }
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - image: kafka-consumer:latest
          name: kafka-consumer
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb/mariadb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kafka-consumer
  type: NodePort
status:
  loadBalancer: { }