apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: kafka-consumer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kafka-consumer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100