apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schemaregistry
  name: schemaregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schemaregistry
  template:
    metadata:
      labels:
        app: schemaregistry
    spec:
      containers:
        - image: confluentinc/cp-schema-registry:latest
          imagePullPolicy: IfNotPresent
          name: schemaregistry
          ports:
            - containerPort: 8085
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schemaregistry
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8085
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: kafka:29092
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: schemaregistry
  name: schemaregistry
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: schemaregistry